### ISSUE TITLE
Publishing to uBO Regional Filters

### ISSUE THREAD

**Issue by designjeevan** [sndsabin/swaccha-adblock-filter#3]
Hi. I have been using these filters for awhile. Most common news sites seem pretty decent without all the annoying ads.
How about submitting these filters to the ublock origin's Regional Ads?
(We can use many technical forums to invite more people to contribute for Nepali sites ads submission. Even reddit too.)

**Comment by sndsabin** [comment]
Hello @designjeevan, cool. Feel free to submit this list to uBlock origin's Regional Ads and other places too. If you wish to collaborate on this, I would be happy to invite you as a collaborator.
